TASK: Refactor controller to not use static fusion path
neos/neos-ui pull request #2920
Opened 2021-07-05 15:32 UTC by daniellienert

The fusion path is now dynamically determined by controller / action
This enables additional actions with separate templates for that controller.

2021-07-20 11:02 UTC, kdambekalns approved these changes
Looks good by reading…

2021-07-25 13:18 UTC, grebaldi requested changes
Hi @daniellienert,

`Resources/Private/Fusion/Backend/Prototypes/RenderConfiguration.fusion` has been moved by this change. That leads to several exceptions like this one:

```
Could not include Fusion file "resource://Neos.Neos.Ui/Private/Fusion/Prototypes/RenderConfiguration.fusion"
resource://Neos.Neos.Ui/Private/Fusion/Backend/Root.fusion:4

Exception Code | 1347977017
-- | --
Neos\Fusion\Exception
2021072513041021ee63
/tmp/neos/Development/SubContextddev/Cache/Code/Flow_Object_Classes/Neos_Fusion_Core_Parser.php
641
Packages/Application/Neos.Fusion/Classes/Core/Parser.php
```

This is because it is referenced here:
https://github.com/neos/neos-ui/blob/050e58b92e8248acd48051eaa9ec0e8abe0e2768/Resources/Private/Fusion/Backend/Root.fusion#L3

Yet, updating the include won't cut it, because the prototype is also used here:
https://github.com/neos/neos-ui/blob/050e58b92e8248acd48051eaa9ec0e8abe0e2768/Resources/Private/Fusion/Prototypes/Page.fusion#L11

So, I'd suggest just to move the file back to its original path.

Other than that, the PR looks good :) 

After moving back `Resources/Private/Fusion/Backend/Prototypes/RenderConfiguration.fusion` to `Resources/Private/Fusion/Prototypes/RenderConfiguration.fusion`, I also recommend rebasing the PR against `master`. After that, E2E Tests are likely to go green again.

2021-07-29 08:14 UTC, Sebobo commented
Probably also a rebase is needed here to make e2e tests work again.

2021-08-11 19:29 UTC, grebaldi approved these changes

2023-12-28 17:47 UTC, markusguenther commented
Also rebased this change and make it work with the latest state.

2023-12-28 17:47 UTC, markusguenther approved these changes
Looks good to me, but I also adjusted something to make it work ;)

2024-01-08 12:27 UTC, mhsdesign commented
Im not super sure that the fusion contents are 1 to 1 the same ... aaand we have to remember when upmerging to use the new 9.0 configuration

2024-01-08 12:29 UTC, mhsdesign approved these changes
no yes its the same

2024-01-13 20:45 UTC, mhsdesign requested changes
But now i fear with the refactoring for 9.0 in https://github.com/neos/neos-ui/pull/3682 (see commit https://github.com/neos/neos-ui/pull/3682/commits/b5b918db273cde421859dc4c9fadcc524ca18f2e) we have waited a bit too long ^^

i wouldnt want to have different backend controller fusion behaviour for 8.3 and 8.4 and 9.0

so instead i would propose to incorporate this cleanup into the mentioned pr or wait for it to be merged and target 9.0

/ cc @grebaldi

2024-01-15 12:44 UTC, grebaldi commented
@mhsdesign:
> so instead i would propose to incorporate this cleanup into the mentioned pr or wait for it to be merged and target 9.0

I'd be fine with targetting `9.0`, but I would propose to merge this PR first. Then I can rebase https://github.com/neos/neos-ui/pull/3682 on `9.0` and incorporate the change accordingly.

2024-01-15 14:34 UTC, mhsdesign commented
> I would propose to merge this PR first

i only agree with this part ;) So i rebased it onto your pr and this pr targets now `feature/multi-app/01-foundation` its wayyy easier this way imo ^^

If you agree please just hit the merge button - as https://github.com/neos/neos-ui/pull/3682 is your pr ^^

2024-01-15 14:35 UTC, mhsdesign approved these changes

2024-01-15 14:54 UTC, merged