BUGFIX: CKEditor now uses em for italic
neos/neos-ui pull request #3195
Opened 2022-10-04 17:06 UTC by JamesAlias

**What I did**
Fixed #2906 
**How I did it**
Created a new CKEditor Plugin for Italic, that uses the original *UI* Plugin but a custom *Editing* Plugin which uses `<em>` for italics.
**How to verify it**
- Open Neos. 
- Open a Page where you can use CKEditor to edit Text.
- Mark text and make it Italic.
- Inspect this text in Devtools.
- The text should be wrapped in an *em* tag

<img width="879" alt="Screenshot 2022-10-04 at 6 29 37 PM" src="https://user-images.githubusercontent.com/1615332/193874466-58ccbff3-2163-49c8-b484-f07ccf5dd71d.png">

2022-10-05 05:57 UTC, Sebobo commented
Thx, works perfect.

But do we have to consider this a breaking change, as people might have relied on creating `i` tags?

2022-10-05 05:57 UTC, Sebobo approved these changes

2022-10-06 07:47 UTC, Sebobo requested changes
IMO we should target this for 8.2 or 9.0

2022-10-07 09:08 UTC, skurfuerst commented
Agreed @Sebobo; I think so too (or we make this configurable!? not sure if we must)

2022-10-07 09:26 UTC, Sebobo commented
@skurfuerst previously we had:
```
config.set('italic', addPlugin(Italic, $get('formatting.em')));
```

And now additionally (using the same option):
```
config.set('italicWithEm', addPlugin(ItalicWithEm, $get('formatting.em')));
```

So don't we even have to remove the first line?

2022-10-08 14:35 UTC, mhsdesign commented
I agree on the breakiness - and no this behaviour (is yet) not configurable - and i would not like it to be configurable -> as this would feel really hacky ^^

2022-10-08 14:36 UTC, mhsdesign commented
about the code: 

> previously we had:
> 
> ```
> config.set('italic', addPlugin(Italic, $get('formatting.em')));
> ```
> 
> And now additionally (using the same option):
> 
> ```
> config.set('italicWithEm', addPlugin(ItalicWithEm, $get('formatting.em')));
> ```
> 
> So don't we even have to remove the first line?

when looking at `ItalicWithEm` its clear why we still need `Italic` as its only an extension on top -> but it doesnt read well imo.

2022-10-08 20:10 UTC, JamesAlias commented
Proposal:

We can introduce an option that activates the conversion of `<i>` to `<em>`.

This way it's not breaking, the feature is available and it also reads better. win, win, win 😉

2022-10-10 08:28 UTC, mhsdesign commented
I asked in slack and the best solution would be


> [...] just document it and let people fix and adjust their CSS. I did add `i` to the CSS for `em` at some point,

> It's such a simple change. Documenting it should suffice.


https://neos-project.slack.com/archives/C050C8FEK/p1665386934728039?thread_ts=1665298045.139539&cid=C050C8FEK

so i think we dont need the config option ;)

2022-10-10 08:36 UTC, Sebobo commented
Then let's target 8.2 and add it to the release notes.

2022-10-10 08:40 UTC, mhsdesign commented
do we need a node migration do adjust everything to `<em>`? 

otherwise t would be mixed `em` and `i`... with a light direction to `em` (on every save)

2022-10-10 08:43 UTC, Sebobo commented
No wouldn't do that. We never migrate the users actual text content. As we also don't know whether they wrote that with CK or it's a custom property with an inspector editor or something

2022-11-24 20:43 UTC, Sebobo approved these changes

2022-11-24 20:44 UTC, Sebobo approved these changes

2022-11-24 20:44 UTC, merged