Feature/8.1 ckeditor download option
neos/neos-ui pull request #3197
Opened 2022-10-05 10:11 UTC by NicoleNitschke

**What I did**

**How I did it**

**How to verify it**

2022-10-06 07:50 UTC, Sebobo commented
Thx!
We will need an additional PR to adjust the docs in `Neos.Neos/Documentation/References/PropertyEditorReference.rst`

2022-10-06 07:50 UTC, Sebobo requested changes
Please target 8.2

2022-10-06 17:10 UTC, crydotsnake commented
> Thx! We will need an additional PR to adjust the docs in `Neos.Neos/Documentation/References/PropertyEditorReference.rst`

I've created the pull request: https://github.com/neos/neos-development-collection/pull/3912

2022-10-07 09:48 UTC, Sebobo approved these changes

2022-10-07 09:59 UTC, Sebobo commented
Works as expected :)

2022-10-07 11:10 UTC, markusguenther approved these changes

2022-10-07 14:01 UTC, merged