TASK: Adjust docs and release script
neos/neos-ui pull request #3204
Opened 2022-10-06 08:57 UTC by markusguenther

We removed the master branch and therefore need adjustments in the docs and scripts.
Also, the Jenkins config needs to be adjusted.

2022-10-06 10:53 UTC, Sebobo requested changes

2022-10-06 10:53 UTC, Sebobo commented on README.md
> +### Installing lattest development
```suggestion
### Installing latest development
```

2022-10-07 06:39 UTC, kdambekalns approved these changes

2022-10-07 09:48 UTC, Sebobo approved these changes

2022-10-07 09:48 UTC, merged