BUGFIX: label of checkbox "auto-publishing" is now clickable and looks nice
neos/neos-ui pull request #3211
Opened 2022-10-06 14:07 UTC by NicoleNitschke

**What I did**
* fix issue #3140 
* made label of checkbox "auto-publishing" clickable and fixed its styling

**How I did it**
* used a pure css solution with absolute positioned label because the react-ui-component checkbox inside the react-ui-component select is buggy

**How to verify it**
* open the publish dropdown and see how it looks now
* click the "auto publish label" - the checkbox will be toggled and the dropdown closed

### Before:
![grafik](https://user-images.githubusercontent.com/11499598/194331430-cf067c3c-0d78-4d05-8a6c-e676e4c26564.png)

### After:
![grafik](https://user-images.githubusercontent.com/11499598/194331321-c9be9e0b-ddba-445d-83d7-e14d0907b086.png)

2022-10-06 14:59 UTC, crydotsnake approved these changes
Hello @NicoleNitschke 

Tested it, and its working fine!

Thanks a lot for the fix!

2022-10-07 09:14 UTC, skurfuerst requested changes
really nice change, just a nitpick :)

2022-10-07 09:14 UTC, skurfuerst commented on packages/neos-ui/src/Containers/PrimaryToolbar/PublishDropDown/index.js
> +                            <Label htmlFor="neos-PublishDropDown-AutoPublish" className={style.dropdownOptionCheckbox}>
Great change! I'd love to have a comment here `{/* A JSX comment */}` explainig why this is needed; so that we understand it when looking at it in the future (also with link to the issue) : )

2022-10-07 09:14 UTC, skurfuerst commented on packages/neos-ui/src/Containers/PrimaryToolbar/PublishDropDown/style.css
> +.dropdownOptionCheckbox {
I'd love to have a comment here {/* A JSX comment */} explainig why this is needed; so that we understand it when looking at it in the future (also with link to the issue) : )

-> answering the question why a *new* checkbox is needed here :)

2022-10-07 09:30 UTC, NicoleNitschke commented on packages/neos-ui/src/Containers/PrimaryToolbar/PublishDropDown/index.js
> +                            <Label htmlFor="neos-PublishDropDown-AutoPublish" className={style.dropdownOptionCheckbox}>
Hi @skurfuerst I added the comment, thx for this feedback! :)

2022-10-07 09:30 UTC, NicoleNitschke commented on packages/neos-ui/src/Containers/PrimaryToolbar/PublishDropDown/style.css
> +.dropdownOptionCheckbox {
Hi @skurfuerst I added the comment, thx for this feedback! :)

2022-10-07 09:47 UTC, skurfuerst commented
@NicoleNitschke sorry, circle CI failed noch ;) (nitpicks)

2022-10-07 10:00 UTC, Sebobo commented
Does this PR interfere with https://github.com/neos/neos-ui/pull/3194 somehow? We merged that some days ago and it also fixes the checkbox alignment.

2022-10-07 10:50 UTC, NicoleNitschke commented
> @NicoleNitschke sorry, circle CI failed noch ;) (nitpicks)

@skurfuerst  CI works now :)

2022-10-07 11:00 UTC, markusguenther commented
> Does this PR interfere with #3194 somehow? We merged that some days ago and it also fixes the checkbox alignment.

The alignment was fixed in Paula's PR, but the click handling does not work for the label. That is fixed here as well.

2022-10-07 11:08 UTC, markusguenther commented
One thing that triggers me is that the dropdown closes after clicking the checkbox or label, but checked Neos 4.3 with the old UI, and it was always the behavior. So for me, it looks fine.

2022-10-07 12:07 UTC, NicoleNitschke commented
> One thing that triggers me is that the dropdown closes after clicking the checkbox or label, but checked Neos 4.3 with the old UI, and it was always the behavior. So for me, it looks fine.

@markusguenther I thought the same as you while fixing this issue, but unfortunately there is no simple solution to fix this. I see 2 ways:
1. Let the Dropdown open with very hacky JS. -> not a good idea
2. Use completely custom components instead of React-Ui-Components Select and Checkbox -> really big change for this feature

Furthermore, this is the only checkbox in the dropdown. For every other dropdown option, the select closes as well. So it could also be confusing for the user, why the dropdown stays open only in this use case. It's a tricky UX case. 
Just wanted to let you know I had thought about it a long time, hope this makes it a little bit less awful for you. :D

2022-10-07 13:53 UTC, markusguenther commented
Yeah, think for this change it is ok and if we want to change the behavior, we should open another PR for that. But it seems that it is there like always ;)

2022-10-07 13:53 UTC, markusguenther approved these changes

2022-10-08 07:19 UTC, merged