TASK: regenerate UriPathSegment in the backend
neos/neos-ui pull request #3229
Opened 2022-10-14 15:21 UTC by PRGfx

**What I did**
To achieve the same behavior in UriPathSegment generation between the UI and the backend (i.e. updating a path segment should use the same logic as when creating a new page), the `NodeUriPathSegmentGenerator` is used in a backend service endpoint.

This allows adjusting the slugification in a consistent way through a single decoration in the backend.

**How I did it**
A new endpoint is added to the BackendServiceController and exposed through the endpoint definitions in the UI.
The UriPathSegment editor then calls that backend to ask for a new slug for the current node title rather than using a javascript library to calculate it in the frontend.

**How to verify it**
This change is introduced against the problem described in #3127, so most notably it will now no longer regenerate `&` to `and`, but it will work better with internationalized transliteration as well, as this was not handled in the previously used JS module.

Maybe we could get rid of the previously used JS module, however I'm unsure about the implications.

This PR originates from #3167.
Resolves #3127

2022-10-14 15:28 UTC, PRGfx commented
@Sebobo you mentioned having adjusted the uri-path-segment generation before. Does this approach make sense to you/do you think customizing the behavior by decorating the `Neos\Neos\Utility\NodeUriPathSegmentGenerator::generateUriPathSegment` would work for such cases or is there another method that should be used?

2022-10-21 07:00 UTC, Sebobo commented on Classes/Controller/BackendServiceController.php
> +        return json_encode($slug);
Use the JSON view feature like this:

```suggestion
        $this->view->assign('value', $slug);
```

2022-10-21 07:07 UTC, Sebobo requested changes
Great change. Left some notes

2022-10-21 07:07 UTC, Sebobo commented on Classes/Controller/BackendServiceController.php
> +    public function transliteratePathSegmentAction(NodeInterface $contextNode, string $text): string
Should be void as we use the JSON view, you can remove the param and returns parts in the doc comment.

```suggestion
    public function transliteratePathSegmentAction(NodeInterface $contextNode, string $text): void
```

2022-10-21 07:07 UTC, Sebobo commented on Configuration/Routes.Service.yaml
> +  uriPattern: 'uri-path-segment'
Describe the action, maybe like this(?):

```suggestion
  uriPattern: 'create-uri-path-segment'
```

2022-10-21 07:07 UTC, Sebobo commented on packages/neos-ui-editors/src/Editors/UriPathSegment/index.js
> -import slugify from '@sindresorhus/slugify';
If we don't need the extension then anymore, we can get rid of it 🥳

2022-10-21 07:30 UTC, mhsdesign commented on packages/neos-ui-backend-connector/src/Endpoints/index.ts
> +            });
just to stay consistent with the rest of the ui ;)

```suggestion
            return ({
                url: routes.ui.service.transliteratePathSegment,
                method: 'POST',
                credentials: 'include',
                headers: {
                    "X-Flow-Csrftoken": csrfToken,
                    "Content-Type": "application/json",
                },
                body: JSON.stringify({
                    contextNode: nodeContextPath,
                    text
                })
            });
```

2022-10-21 07:57 UTC, PRGfx commented
For every consistency issue there was an example I went off of ^^ tbf I didn't evaluate the "most common" patterns.

Before I go and make these changes: are there preferences on commit history, i.e. so far I split my changes into separate commits based on concerns - should I rather clean these up or just push the suggested changes?

2022-10-21 08:04 UTC, Sebobo commented
Your commits look great so far. But IMO the main change should be marked as `FEATURE:` instead of `TASK:`.
Would be best to group all suggestions into one commit.

2022-10-21 11:18 UTC, PRGfx commented
As I understood you prefer it being squashed in the end, I just pushed it separately for now.

That changing dependencies includes the .yarn/cache/ items is correct?

2022-10-21 11:27 UTC, Sebobo commented
Yes that is correct.
We prefer multiple commits if they help understanding the individual steps during review and later on during debugging.
But if there are many "fixup" "fixed another bug" etc. those should be merged into one. I use Gittower and try to clean up, reorder and combine my commits in my PRs before finally giving them to review.

2022-10-23 08:23 UTC, PRGfx commented
I squashed the main commits into a "FEATURE" commit. To me the main feature of this PR does not work with only parts of that.

Thank you for your support.

2022-10-23 10:44 UTC, mhsdesign commented
Hi - i just tested it and it works fine ;)

https://user-images.githubusercontent.com/85400359/197387060-d9c666bf-af04-421a-bf8e-2423b265efc7.mp4

but since this is now async im wondering about the UX on slower connections / server ...
is this behaviour realistic?


https://user-images.githubusercontent.com/85400359/197387513-0dbc3a26-ffb6-4a7a-b654-44ddf931c636.mp4


i played with this:


https://user-images.githubusercontent.com/85400359/197387550-46d99c9b-61a2-441b-aab3-ad2608925bb7.mp4


but its not so cool for fast responses ... (or is it?)

https://user-images.githubusercontent.com/85400359/197387641-ed283787-59de-4a4b-b00c-a5b6a057257b.mp4

2022-10-23 12:48 UTC, PRGfx commented
There was a question in slack regarding refreshing anchor links and I thought about abstracting this editor into something that could refresh from an arbitrary data source.
However I'm not sure if that would be implemented with something like existing data-source options + client eval and preconfiguration or whether that would be some derived editor built with a specific callback.

I thought about the missing feedback on this editor as it is. Maybe it is enough to disable the button until resolved, if that has some distinctive look.
Regarding the spinner there is this idea to just start it after a few milliseconds in case it returns early, but then of course it might act the same, just a bit delayed ^^

2022-10-24 07:18 UTC, Sebobo commented
I think disabling the input and spinning is best. IMO this is an action that doesn't occur all the time and the editor waits for the result.
But we might add a transition to the background color, then it wouldn't hurt the eye.

2022-10-24 19:31 UTC, PRGfx commented
The button becomes disabled now and the icon spins while the process is busy.
Thank you for your changes @mhsdesign! I changed the the iconButton changes to accept iconProps instead of a complete icon and renamed the state variable to make it a bit more generic.

@Sebobo changing the style for inputs exceeds the scope of this issue I think. An animation would need to be set for the base background and thus drastically change the behavior for regular focusing of inputs I think.

2022-10-25 06:58 UTC, Sebobo commented
Thx!

One more thing we should clean up, you named the method in 3 different ways right now:

* generate-uri-path-segment
* regeneratePathSegment
* transliteratePathSegment

I think we should have only one variant. `transliterate` doesn't sound right to me, therefore I personally prefer `generate` or `regenerate`.

What do you guys think?

2022-10-25 07:03 UTC, mhsdesign commented
yes i stumbled on that too - but forgot to mention it ^^
just name everything from route to action something like `generate-uri-path-segment`

2022-10-25 09:05 UTC, PRGfx commented
Fair point. The editor method is a bit out of line now but I want to avoid the same name for different functions.

2022-11-07 09:32 UTC, PRGfx commented
Hey, are there any more changes you want done, anything I can/should do?

2022-11-07 09:57 UTC, mhsdesign approved these changes
Thx for the adjustments!

2022-11-07 09:57 UTC, mhsdesign commented on packages/react-ui-components/src/IconButton/iconButton.tsx
> +    readonly iconProps?: React.ComponentProps<typeof Icon>;
we discussed whether to use slots or additionalProps but it seems to boil down to personal preference - and i dont know if we decided in the ui already for the one or other pattern

im team "slots" but this is also fine with me (as its not such a critical change)

2022-11-09 09:28 UTC, Sebobo approved these changes

2022-11-09 09:36 UTC, mhsdesign commented on packages/react-ui-components/src/IconButton/iconButton.tsx
> +    readonly iconProps?: React.ComponentProps<typeof Icon>;
another alternative would be `isIconSpinning` or sth ...

2022-11-10 08:22 UTC, merged