BUG: `<Tabs activeTab={2}/>` doesnt work on first render
neos/neos-ui pull request #3399
Opened 2023-03-01 13:07 UTC by mhsdesign

**What I did**

**How I did it**

**How to verify it**

2023-03-01 13:10 UTC, mhsdesign commented
```
public constructor(props) {
    super(props)
    this.state.activeTab = props.activeTab
}
```

should do but ts doesnt like it ^^ (state is readonly)

2023-03-30 15:49 UTC, Sebobo requested changes
Looks good to me. Can you add a test to verify the functionality with the string based id?
Seems all tests only use the numbers.

2023-03-30 15:53 UTC, Sebobo commented on packages/react-ui-components/src/Tabs/tabs.tsx
> +            this.props.onActiveTabChange(activeTab);
It would be better IMO to set the state before calling the callback to prevent the callback from interfering with the functionality. Maybe just a theoretical problem. Not sure.

2023-03-30 15:56 UTC, mhsdesign commented on packages/react-ui-components/src/Tabs/tabs.tsx
> +            this.props.onActiveTabChange(activeTab);
yeah i though about it too, most correct way would be:

```
this.setState({activeTab}, () => {
 this.props.onActiveTabChange(activeTab)
})
```

2023-03-30 15:59 UTC, mhsdesign commented on packages/react-ui-components/src/Tabs/tabs.tsx
> +            this.props.onActiveTabChange(activeTab);
the order of 

```
this.props.onActiveTabChange(activeTab)
this.setState({activeTab})
```

```
this.setState({activeTab})
this.props.onActiveTabChange(activeTab)
```

shouldnt matter imo as the state is only updated after rerender or sth ...

2023-03-30 16:13 UTC, Sebobo commented on packages/react-ui-components/src/Tabs/tabs.tsx
> +            this.props.onActiveTabChange(activeTab);
There are various effects that can be used when we switch to hooks, or whatever is cool until then. 
I just wonder like throwing an error in the callback or running some operation and the UI would be blocked due to that. As I said, sounds a bit dumb, but 🤷🏻‍♂️

2023-03-30 17:07 UTC, mhsdesign commented on packages/react-ui-components/src/Tabs/tabs.tsx
> +            this.props.onActiveTabChange(activeTab);
okay this it is:
```js
this.setState({activeTab}, () => {
 this.props.onActiveTabChange(activeTab)
})
```

2023-03-30 19:21 UTC, mhsdesign commented
> Can you add a test to verify the functionality with the string based id?

Aba natürlich

2023-03-31 06:57 UTC, Sebobo approved these changes
Looks good by reading!

2023-03-31 07:10 UTC, merged