BUGFIX: Prevent error when initialising a node that is not in the store yet
neos/neos-ui pull request #3575
Opened 2023-07-10 16:04 UTC by Sebobo

This can happen when a node is added via content references, as the backend doesn’t have any nodedata yet for the nodes that are rendered in the guest frame.

Resolves: #3574

2023-07-10 16:05 UTC, Sebobo commented
An alternative would be to return the necessary node data before the html is rendered. Not sure if that is viable though.

2023-07-10 16:31 UTC, dlubitz approved these changes
I tested the fix locally and it solves at the issue.

2023-07-10 17:18 UTC, mhsdesign requested changes
I can confirm that this works, but i think it should be easily doable to fetch the required node informations.

In the case https://github.com/neos/neos-ui/issues/3574 we dont need any inline interaction, but one can never know if some one expects it or if we would currently silently ignore other edge cases (what will be hard to debug)

calling `neos.endpoints.getAdditionalNodeMetadata` after the out of band rendering should do ...

2023-07-10 17:36 UTC, mhsdesign commented
Hmm this doesnt do it ...

to be pasted after:

https://github.com/neos/neos-ui/blob/e89cc22ddb67d900e557430d300392e11f61152a/packages/neos-ui/src/manifest.js#L544

```js
        const {getAdditionalNodeMetadata} = backend.get().endpoints;

        const uninitializedNodes = [];

        for (const el of children) {
            const contextPath = el.getAttribute('data-__neos-node-contextpath');
            if (!selectors.CR.Nodes.byContextPathSelector(contextPath)(store.getState())) {
                uninitializedNodes.push(contextPath);
            }
        }

        if (uninitializedNodes.length) {
            const additionalNodeMetadata = await getAdditionalNodeMetadata(uninitializedNodes);

            if (additionalNodeMetadata) {
                store.dispatch(actions.CR.Nodes.merge(additionalNodeMetadata));
            }
        }
```

maybe the information of `getAdditionalNodeMetadata` is not that helpfull, it only seems to return partial nodes ...

2023-07-11 07:41 UTC, Sebobo commented
@mhsdesign I now added warnings, so when debugging something we would at least have some information.

2023-07-11 07:56 UTC, dlubitz commented
This is the PR for fusion side: https://github.com/neos/neos-development-collection/pull/4399

2023-07-11 08:22 UTC, mhsdesign approved these changes

2023-07-11 08:30 UTC, merged