TASK: Marry `DialogWithOverlay` & `DialogWithoutOverlay`
neos/neos-ui pull request #3579
Opened 2023-07-11 22:29 UTC by mhsdesign

**What I did**

**How I did it**

**How to verify it**

2023-07-11 23:08 UTC, crydotsnake requested changes
Looks good!

But i would make the border orange in this case :)

2023-07-12 08:07 UTC, mhsdesign commented
@crydotsnake adjusted see https://github.com/neos/neos-ui/issues/3531#issuecomment-1632040173 ;)

2023-07-12 08:10 UTC, crydotsnake approved these changes
Works great! 💙

2023-07-12 08:27 UTC, grebaldi approved these changes
Code looks :+1: and I was able to verify manually that both closing the dialog by clicking outside and closing the dialog by  escape key are prevented when there's input in the node creation dialog.

Very nice work, @mhsdesign! :)

2023-07-12 11:04 UTC, Sebobo approved these changes
Could be breaking if someone used the exported DialogWithoutOverlay which we don't explicitly expose in the api, but let's assume this didn't happen.

2023-07-12 11:05 UTC, merged