TASK: Add moment locales to have a localized DatePicker
neos/neos-ui pull request #3596
Opened 2023-08-15 12:54 UTC by JamesAlias

**What I did**
A customer notized that the DatePicker Editor is not localized (anymore?).
So I added the missing moment locales.

**How I did it**
Our current DatePicker is localized via `moment` locales, so I had to import them.
This sadly adds ~200kb to the bundle.

We could also only import specific locales (e.g. `de`, etc.) to keep the bundle size impact smaller.

**How to verify it**
Change language in user setting and open the DatePicker Editor in the Neos Inspector.

2023-08-16 07:59 UTC, skurfuerst approved these changes
looks good to me

2023-08-16 08:04 UTC, Sebobo commented
I would prefer to not include **all** locales and make this more easily configurable so we can extend whenever additional ones are really required. 

I guess the 200KB contain many many more format types than we even display. Is it somehow possible to just select the ones we actually need for the picker?

And if it's a bugfix, then we should apply it to an older version, no?

2023-08-16 08:08 UTC, mhsdesign requested changes
If we really add ~200kb to the minified bundle id say this is really a lot. I dont know how to justify this 😭 

Is this fix related to https://github.com/neos/neos-ui/issues/2467? 

and speaking of the date picker: to solve https://github.com/neos/neos-ui/issues/3391 we need either way a roundtrip to the server. Maybe we can generally remove some date calculating logic from js and move it to the server? (and thus save lots of js? ^^)

2023-08-16 08:20 UTC, Sebobo commented
Also something to look at https://dockyard.com/blog/2020/02/14/you-probably-don-t-need-moment-js-anymore

2023-08-16 08:35 UTC, skurfuerst commented
Hm, I feel we are coming from the "100s" to the "1000s".

We are right now looking at fixing the issue of the customer that the weeks start at Sundays in the date picker - which he finds confusing. I am totally fine with doing a bit more to get this into the core, but I would NOT right now remove moment.js or anything like that.

If that's a blocker for you, then we won't push this forward anymore but look how to solve this otherwise, but only in the project then @Sebobo @mhsdesign. I'd be curious about your take on this :)

I see the "pain" of the added 200kb; and I am totally fine reducing this a bit if this is feasible.

2023-08-16 08:37 UTC, Sebobo commented
Sorry, I didn't mean we have to remove momentjs now, that can be another task. But we spend so much time on reducing the bundle and I don't want to make it bigger after a 5 minute discussion.

If we for now add a few locales that cover 99% of our users and only slightly increase the bundle, I'm fine. Then we should have a follow-up task for Neos 9.x to fix this properly.
So many projects have problems mit the size of momentjs and try to get rid of it.

2023-08-16 08:39 UTC, skurfuerst commented
Awesome - thanks @Sebobo for your clarification ❤️

2023-08-16 08:40 UTC, JamesAlias commented
All good points.

I can only add the german locale for now, as it fixes my current issue.

Moving away from momentjs would be nice, but it's a peer dependency of the DatePicker component.

2023-08-16 08:46 UTC, mhsdesign commented
I would also be fine as a fix to only additionally include the "de" locale. I was also just making sure that we dont take any rushed steps after having optimized the bundle size so long.

2023-08-16 08:48 UTC, mhsdesign commented
Does this bug also occur in 7.3? If so id like to have it back-ported and declared as `BUGFIX`

2023-08-16 10:16 UTC, bwaidelich commented
On the risk of missing the point: Maybe it's an option to use built-in [`Intl.*`localizations](https://dockyard.com/blog/2020/02/14/you-probably-don-t-need-moment-js-anymore) of the browser and only fall back to custom locales for older browsers (if required)

2023-08-16 13:28 UTC, JamesAlias commented
@mhsdesign the bug seems to be introduced with our move from webpack to esbuild.
Looks like webpack just bundled the whole momentJs bundle (including locales).

2023-08-16 14:05 UTC, simonschaufi commented
Moment is heavy. I use date-fns instead. Mayer this is a good alternative?

2023-08-16 14:08 UTC, JamesAlias commented
date-fns is also my go-to replacement for momentJs but the DatePicker Component is depending on momentJs.
So we would have to change the DatePicker component as well.

2023-08-16 17:05 UTC, skurfuerst commented
@mhsdesign needing your second review :)

2023-08-17 09:54 UTC, mhsdesign commented
> the bug seems to be introduced with our move from webpack to esbuild.

then we should target 8.2 ;)

2023-08-23 09:31 UTC, baschny commented
Maybe the "Datepicker" should be replaced altogether? UX-wise it is still "painful", see also #1503 where this has been discussed before. Is there still no better alternative in react, which at the same time is not dependant on momentJS?

🤔

2023-08-25 10:27 UTC, mhsdesign approved these changes
lgtm ;)

2023-08-25 10:36 UTC, merged