TASK: Refactor UI Validator translations to Neos.Neos.Ui package
neos/neos-ui pull request #3614
Opened 2023-09-08 23:30 UTC by crydotsnake

**What I did**

I added the translations of our validators from the Neos.Neos package directly too the Neos.Neos.Ui package.

**How I did it**

Copied the translations over, and adjusted the Validator Components to load the correct translations.

**How to verify it**

Checkout this PR in combination with:

and add a Validator to your NodeType. You should see, that the translation is still working.

2023-09-09 13:51 UTC, mhsdesign commented
There is a failing unit test caused by this change (see the end of the console output):

```
Summary of all failing tests
FAIL packages/neos-ui-validators/src/Count/index.spec.js
  ● [1, 2, 3, 4] should result in an error message for min: 1 max: 3

    expect(received).toEqual(expected) // deep equality

    - Expected  - 0
    + Received  + 2

      Object {
        "id": "content.inspector.validators.countValidator.countBetween",
    +   "packageKey": "Neos.Neos.Ui",
        "params": Object {
          "maximum": 3,
          "minimum": 1,
        },
    +   "sourceName": "Main",
      }

      at Object.<anonymous> (packages/neos-ui-validators/src/Count/<stdin>:66:26)


Test Suites: 1 failed, 134 passed, 135 total
Tests:       1 failed, 708 passed, 709 total
Snapshots:   50 passed, 50 total
Time:        140.399 s
Ran all test suites.
```

2023-09-10 07:11 UTC, crydotsnake commented
> There is a failing unit test caused by this change (see the end of the console output):
> 
> ```
> Summary of all failing tests
> FAIL packages/neos-ui-validators/src/Count/index.spec.js
>   ● [1, 2, 3, 4] should result in an error message for min: 1 max: 3
> 
>     expect(received).toEqual(expected) // deep equality
> 
>     - Expected  - 0
>     + Received  + 2
> 
>       Object {
>         "id": "content.inspector.validators.countValidator.countBetween",
>     +   "packageKey": "Neos.Neos.Ui",
>         "params": Object {
>           "maximum": 3,
>           "minimum": 1,
>         },
>     +   "sourceName": "Main",
>       }
> 
>       at Object.<anonymous> (packages/neos-ui-validators/src/Count/<stdin>:66:26)
> 
> 
> Test Suites: 1 failed, 134 passed, 135 total
> Tests:       1 failed, 708 passed, 709 total
> Snapshots:   50 passed, 50 total
> Time:        140.399 s
> Ran all test suites.
> ```

Hm. How could i fix this?

2023-09-10 11:18 UTC, crydotsnake commented
Now e2e are failing 😅

2023-09-10 12:31 UTC, mhsdesign commented
Well thats why they dont work yet ^^ (see 9.0 branch) #3546

2023-09-11 14:24 UTC, crydotsnake commented
Ahh i see :) So this PR should be fine then.

2023-09-21 10:51 UTC, mhsdesign commented
ill give you my approval after we have merged the e2e ;) maybe they also cover the labels somewhere ^^

2023-09-23 07:29 UTC, mhsdesign commented
@crydotsnake you can now rebase this pr or merge master and the tests should be green ;)

2023-09-23 13:29 UTC, crydotsnake commented
Green light ;) @mhsdesign

2023-10-21 08:53 UTC, dlubitz requested changes
For the translation we use Weblate. 

We are just allowed to change the EN-files in the code and Weblate will catch them up and create the corresponding keys in other languages.

Not sure how to proceed with this "move" of keys, but I guess there is something in weblate to do so. Otherwise we have to copy them there manually.

See also: https://github.com/neos/neos-development-collection/pull/4493#issuecomment-1713289700

2024-01-13 18:48 UTC, mhsdesign commented
FYI found this issue which might be solved https://github.com/neos/neos-ui/issues/2421

2024-10-21 07:42 UTC, bwaidelich commented
What's the state with this one?

2025-10-08 10:52 UTC, closed without merging