TASK: Use `docker-compose` rather than `docker compose`
neos/neos-ui pull request #3718
Opened 2024-02-15 15:01 UTC by grebaldi

I've been using `start-neos-dev-instance.sh` for local E2E tests as of late and stumbled upon an issue.

The `Tests/IntegrationTests/start-neos-dev-instance.sh` script refers to docker-compose thusly:
https://github.com/neos/neos-ui/blob/fe77db35c48e886b7a0421ccf3e2f0da6d098e52/Tests/IntegrationTests/start-neos-dev-instance.sh#L5-L8

Now, the comment `# use the docker composer plugin` sounds to me like a misconception, but apart from that there's the rather unusual `docker compose` call (without dash).

I suppose that in some environments docker-compose works like a docker plugin, so that it is available as a subcommand of the docker cli. But usually it is invoked via its own CLI binary `docker-compose`.

Since `docker compose` stopped working on my machine (though I'm not sure whether it ever did work), I'd like to suggest to change this call to `docker-compose`, which *should* work everywhere.

2024-02-15 16:37 UTC, mhsdesign commented
The comment has to be my foult, though it was brought out of context :D https://github.com/neos/neos-ui/pull/3369/commits/02c788669641c58228b1f4d8cc658851c847b486

I remember changing this like you suggested, but i think this would be the legacy syntax (with dash) ... and robert and me figured that it works without, thus it was removed again ...

all part of this squashed pr: https://github.com/neos/neos-ui/pull/3369

2024-02-16 14:52 UTC, kdambekalns requested changes
`docker compose` is the proper way to do it. See https://docs.docker.com/compose/reference/ and https://docs.docker.com/compose/migrate/

2024-02-16 15:00 UTC, grebaldi commented
Yet it doesn't work as expected:

```sh
> docker --version
Docker version 24.0.5, build 24.0.5-0ubuntu1~22.04.1

> docker compose
docker: 'compose' is not a docker command.
See 'docker --help'
```

I'm pretty sure this came with an update. Maybe a problem with `docker` itself?

`docker-compose` works without a problem :shrug:

2024-02-16 15:06 UTC, grebaldi commented
**UPDATE:**

I found the issue. On Ubuntu, you need to install an additional package for this to work:

```sh
sudo apt install docker-compose-v2
```

source: https://github.com/docker/compose/issues/8630#issuecomment-1825685695

2024-02-16 15:06 UTC, closed without merging

2024-02-16 15:51 UTC, kdambekalns commented
With Homebrew I once did this, when I dumped Docker Desktop:

```
mkdir -p ~/.docker/cli-plugins
ln -sfn /opt/homebrew/opt/docker-compose/bin/docker-compose ~/.docker/cli-plugins/docker-compose
```