Bugfix/3477 infinite loading indicator and redirect
neos/neos-ui pull request #3748
Opened 2024-03-13 16:45 UTC by 73nici

**What I did**
Remove the origin from the iframe href to check whether the iframe needs to be reloaded. Because `props.src` now does not contain the origin.

**How to verify it**
Edit `Packages/Neos/Neos.Neos/Classes/Domain/Service/FusionService.php` and add

```php
        \Neos\Flow\var_dump($site);
        die();
``` 

to the `createFusionConfigurationFromSite` function.
After that every site dumps the site variable, resulting in an endless reload, which is fixed by this bugfix.

This fixes partly  #3477

2024-04-03 20:15 UTC, mhsdesign approved these changes
I have to look at this again, it seems after navigating via the dom the infinite reloads continue

2024-04-03 20:16 UTC, mhsdesign requested changes
.

2024-04-11 18:03 UTC, 73nici commented
Hey @mhsdesign,
can i still help with something to get this PR merged :).

2024-04-27 08:52 UTC, mhsdesign approved these changes
Thanks now it works. Neither the inline navigation (via the iframe) nor the navigation via the document tree leads to endless exception flodding like currently:

https://github.com/neos/neos-ui/assets/85400359/b02ecfca-8c94-4d85-9aed-9eb1a570e7b2

That way we restored the same behaviour as in Neos 8.3

2024-04-29 08:10 UTC, merged