BUGFIX: Change update interval on CKEditor
neos/neos-ui pull request #3751
Opened 2024-03-14 14:05 UTC by Alvadda

Currently, the CKEditor send the onChange event after user stops typing for 500ms, this results in a lot of unnecessary events that bloats the server. 

This adjustment was initially made in response to a new server behavior observed in Neos9, where the server temporarily blocks incoming change requests during publishing processes. Extending the debounce interval aims to mitigate the risk of overlap between change requests and publishing operations.

**What I did**
The debounce timer has been extended from 500ms to 1500ms. This reduces the frequency of onChange events, thereby decreasing server load.

An additional onChange event has been introduced to trigger whenever the editor loses focus. This ensures that all changes are captured, even if the user does not pause in their typing.

**How to verify it**
Engage with the CKEditor by typing. Upon ceasing typing, observe that the publish button (located in the top right corner) indicates a change was made, after a delay of 1500ms.

While typing in CKEditor, shift focus to another element before the 1500ms debounce period concludes. The publish button should still update to reflect a change, ensuring that all modifications are captured accurately.

2024-03-26 15:29 UTC, grebaldi requested changes
Hi @Alvadda,

thanks for taking care of this!

I've pointed out one leftover `console.log` in the comments.

Additionally, could you please take a look at this test:
https://github.com/neos/neos-ui/blob/2c409b5e3a3cc5b9eb384a2ccd3ec249131890e5/Tests/IntegrationTests/Fixtures/1Dimension/createNewNodes.e2e.js#L178-L195

If you change the wait times that are currently set at `600` to `1600`, the E2E tests will turn green :)

2024-03-26 15:29 UTC, grebaldi commented on packages/neos-ui-ckeditor5-bindings/src/ckEditorApi.js
> +            console.log('editor.ui', editor.ui);
```suggestion
```

2024-07-08 11:52 UTC, grebaldi commented
I've altered the wait times in the E2E tests, and they're green now :tada: 

I'm gonna merge this :)

2024-07-08 11:53 UTC, grebaldi approved these changes

2024-07-08 11:53 UTC, merged

2024-07-17 11:41 UTC, mhsdesign commented
I fear this change introduced a regression which was not found during testing nor is covered by e2e.
I noticed that simply clicking into a ckeditor text field and afterwards selecting something else triggered a change.
This happens for every text element:

<img width="274" alt="image" src="https://github.com/user-attachments/assets/cb64c15b-de57-44f8-96ad-783081101487">

2024-12-10 08:00 UTC, mhsdesign commented
Fyi with ckeditor 44 we could actually experiment with using the autosave plugin which does exactly that :O https://ckeditor.com/docs/ckeditor5/44.0.0/features/autosave.html