TASK: Add docs for contribution getting started
neos/neos-ui pull request #3798
Opened 2024-06-01 12:03 UTC by JamesAlias

**What I did**

**How I did it**

**How to verify it**

2024-06-03 09:20 UTC, Sebobo approved these changes

2024-06-03 10:55 UTC, grebaldi approved these changes

2024-06-05 20:23 UTC, crydotsnake requested changes

2024-06-05 20:23 UTC, crydotsnake commented on README.md
> +```
One little nitpick 🙂 

```suggestion
```bash
```

2024-06-05 20:23 UTC, crydotsnake commented on README.md
> +Run `make setup`. To check what commands are executed have a look at the `Makefile` in the root of this repo.
```suggestion
Run `make setup`. To check what commands are executed have a look at the `Makefile` in the root of this repository.
```

2024-09-30 08:57 UTC, markusguenther approved these changes

2024-09-30 08:58 UTC, merged