FEATURE: Make RightSideBar inspector resizable
neos/neos-ui pull request #3828
Opened 2024-07-15 09:16 UTC by c4ll-m3-j4ck

This uses some small html hacks to make RightSideBar resizable in a comparable way to LeftSideBar.

**What I did**
I added the resize-attribute to RightSideBar and moved the resize-handle to the left edge of the sidebar.

**How I did it**
Updated `Neos.Neos.Ui/packages/neos-ui/src/Containers/RightSideBar/style.module.css`

**How to verify it**
<img width="323" alt="Bildschirmfoto 2024-07-15 um 11 15 17" src="https://github.com/user-attachments/assets/92db2245-e2dd-4344-b230-6b93500b7096">

2024-07-24 11:09 UTC, Sebobo commented
We could target this for 8.4 if you like?

2024-07-24 11:30 UTC, c4ll-m3-j4ck commented
Sure, why not, I’d still need this for 9.0 as well though, but if we could upmerge afterwards, I’m totally fine with that!

2024-07-29 13:21 UTC, mhsdesign commented
Yeah we do frequent upmerges so dont worry ;) Also by merging it in 8.4 more people are able to test this ^^

2024-07-31 12:58 UTC, c4ll-m3-j4ck commented
@Sebobo I've changed the target branch, is there a planned timeframe for the next release?

2024-08-01 08:31 UTC, mhsdesign commented
Hi as we are "down targeting" a pr the actual changes of you have to be cherry-picked on a fresh 8.4 as otherwise 8.4 will become a full 9.0 after the merge

2024-08-03 11:16 UTC, mhsdesign reviewed
So i did the git cherrypick magic to target 8.4 ;) When testing i noticed that it doesnt work on safari, but so does the left side bar see bug: https://github.com/neos/neos-ui/issues/3556 (there is even a possible fix for this ...)



On a chromium based browser the resizing does work though as expected:


https://github.com/user-attachments/assets/1b8a4843-bfb2-4e9d-922b-b58fdc3405ec


But i noticed a small pixel shift, the discard and apply buttons appear to take up more space and the box seems wider and a little off:

before:

<img width="382" alt="image" src="https://github.com/user-attachments/assets/6abaaab3-8b43-47a2-8c74-3e80471c5bc7">


after:

<img width="382" alt="image" src="https://github.com/user-attachments/assets/3e480e53-a502-4507-816b-8c65e3796a0f">

2024-08-05 07:29 UTC, c4ll-m3-j4ck commented
Hey @mhsdesign 
Thank you for the in-depth review, I'll take a look at whats causing these issues! If there is a fix for the safari issue, maybe I can fix that for the left sidebar as well!

2024-09-16 08:52 UTC, Sebobo requested changes
For me in Chrome the action bar is a few pixels wider with this change due to the direction properties:

![CleanShot 2024-09-16 at 10 50 06@2x](https://github.com/user-attachments/assets/fa8337d1-39bf-431a-baa9-f2594c9b3df2)

2025-04-01 20:16 UTC, Sebobo approved these changes

2025-04-01 20:31 UTC, jonnitto approved these changes

2025-04-01 20:34 UTC, merged

2025-04-01 20:37 UTC, Sebobo commented
Thx again @c4ll-m3-j4ck, sorry it took so long ❤️