BUGFIX: Always bundle custom svgs instead of using `resource://` paths
neos/neos-ui pull request #3836
Opened 2024-08-08 12:09 UTC by mhsdesign

Resolves: https://github.com/neos/neos-ui/issues/3616

**What I did**

The custom icons are now included into the bundle instead of requested by path.

<img width="445" alt="image" src="https://github.com/user-attachments/assets/d7d9e397-586a-4229-aff2-d311abb708f8">

Also to unify things and simplify the build-stack, the Neos icon is now also bundled as plain svg instead of data-url:

<img width="219" alt="image" src="https://github.com/user-attachments/assets/09cc100c-51d2-4bb8-966d-2ca292b2b272">

Surprisingly i could not observer any pixel shifting. So this should be 100% the same visual look.

**How I did it**

**How to verify it**

2024-08-09 06:23 UTC, Sebobo requested changes
Works and looks great, but I don't see yet how we can deprecate the now old `ResourceIcon` if the new one does something else and from what I see doesn't support custom icons.

2024-08-09 06:23 UTC, Sebobo commented on packages/react-ui-components/src/Icon/resourceIcon.tsx
> + * @deprecated please refrain from using resource paths
The `Icon` component is still using the ResourceIcon when defining custom icons in yaml. What is the intended replacement?

2024-08-12 11:30 UTC, mhsdesign commented
As written in https://github.com/neos/neos-ui/issues/2092

> Case (3.) is more complicated, I'm afraid. The `<ResourceIcon/>` is a specialization of the (unfortunately public API) `<Icon/>`-component. We will need to deprecate its behavior, and (prior to that) find a way to allow for custom Icon URIs that can be resolved on the server side (we'll some sort of configurable mapping thing here).

My idea is to deprecate the behaviour but thats just for us and without real effect obviously.
To get rid of all usages we will - and i will plan do so - make the `NodeTypeSchemaBuilder` transform all `resource://` paths on the server. 

That will leave us with no more usages of client `resource://` paths. Wdyt?

2024-08-12 11:41 UTC, Sebobo approved these changes
Works on my machine <3

2024-08-12 12:07 UTC, mhsdesign commented on packages/neos-ui-editors/src/Editors/Image/resource/dummy-image.dataurl.svg
This is now duplicated here and in `Neos.Neos` but yeah there is no way around this ... and it somehow belongs here imo

2024-08-28 14:08 UTC, grebaldi approved these changes
Looks & works very well :)

2024-09-02 11:55 UTC, merged